apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress.fullname" . }}
stringData:
  DB_HOST: {{ .Values.db.host }}
  DB_NAME: {{ .Values.db.name }}
  DB_TABLE_PREFIX: {{ .Values.db.tablePrefix }}
  DB_USER: {{ .Values.db.user }}
  DB_PASSWORD: {{ .Values.db.password }}
  DB_CHARSET: {{ .Values.db.charset }}
  DB_COLLATE: {{ .Values.db.collate }}
  AUTH_KEY: {{ .Values.secrets.authKey }}
  AUTH_SALT: {{ .Values.secrets.authSalt }}
  SECURE_AUTH_KEY: {{ .Values.secrets.secureAuthKey }}
  SECURE_AUTH_SALT: {{ .Values.secrets.secureAuthSalt }}
  LOGGED_IN_KEY: {{ .Values.secrets.loggedInKey }}
  LOGGED_IN_SALT: {{ .Values.secrets.loggedInSalt }}
  NONCE_KEY: {{ .Values.secrets.nonceKey }}
  NONCE_SALT: {{ .Values.secrets.nonceSalt }}